# python runtime
FROM python:3

# working directory in container
WORKDIR app

# copy the current directory contents into the container at /app
COPY . /app

# set the command to run
CMD ["python", "main.py"]